### ISSUE TITLE
HG00096.xxx.bam is no more

### ISSUE THREAD

**Issue by darked89** [GELOG/docker-ubuntu-adam#2]
Hello,

seems that ppl @ftp.1000genomes.ebi.ac.uk moved from bam format and left only cram files in this directory:
/vol1/ftp/data/HG00096/alignment/

Also downloading > 15Gb file (CRAM is +14Gb) using ftp can take long time. The 100genomes project provides an access with Aspera client: http://www.1000genomes.org/faq/how-download-files-using-aspera

Hope it helps,

Darek Kedra

**Comment by davidonlaptop** [comment]
I am not sure to understand what you're trying to express. Do you have a specific problem with ADAM or our docker image for ADAM ?

**Comment by darked89** [comment]
Sorry, I should have been more precise. I have attempted to run Docker image for ADAM. One of the examples (Download a larger BAM) relies on downloading file mentioned above. File do not exist. Obviously one can get another BAM from another location, but then we add an extra variable. 

Best,

DK

**Comment by davidonlaptop** [comment]
Hum you're right, it seems the BAM file is gone. I'm pretty sure there was a file at that URL before though. I've randomly checked at random folders, but I only found CRAM files.

I am not sure if ADAM supports CRAM files.

**Comment by darked89** [comment]
Fixed: the 1000genomes ppl changed the location. Now it is:
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00096/alignment/
And the selected file (HG00096.chrom20.ILLUMINA.bwa.GBR.low_coverage.20120522.bam) is just 300Mb, so no need to mess around with Aspera.

**Comment by davidonlaptop** [comment]
Thanks Darek! I'll have a look

**Comment by davidonlaptop** [comment]
I am moving the instructions with your corrected path to a new issue (see #4), and I'll delete it from the main README.
