### ISSUE TITLE
vcf2adam error

### ISSUE THREAD

**Issue by zhanxw** [GELOG/docker-ubuntu-adam#5]
Hello, 

I am using docker image to convert VCF to ADAM format, using this command (below). 
I got the error complaining file format. Is there a way to solve this?

**Data**

chr1.bcf is get from: 

bcftools convert -o chr1.bcf -O b ALL.chr1.phase3_shapeit2_mvncall_integrated_v5.20130502.genotypes.vcf.gz

**The beginning lines look like**
## contig=<ID=5,assembly=b37,length=180915260>

....

**Commands**

> docker run -it -v /home/zhanxw/proj/quickSeq/data:/data gelog/adam /bin/bash
> root@d76e9fa25259:/# adam-submit vcf2adam /data/chr1.bcf /data/chr1.adam
> Using ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain
> Using SPARK_SUBMIT=/usr/local/spark/bin/spark-submit
> Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
> 16/02/10 23:56:01 INFO ADAMMain: ADAM invoked with args: "vcf2adam" "/data/chr1.bcf" "/data/chr1.adam"
> 16/02/10 23:56:01 INFO SparkContext: Running Spark version 1.4.1
> 16/02/10 23:56:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> 16/02/10 23:56:01 INFO SecurityManager: Changing view acls to: root
> 16/02/10 23:56:01 INFO SecurityManager: Changing modify acls to: root
> 16/02/10 23:56:01 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
> 16/02/10 23:56:02 INFO Slf4jLogger: Slf4jLogger started
> 16/02/10 23:56:02 INFO Remoting: Starting remoting
> 16/02/10 23:56:02 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@10.0.0.1:38874]
> 16/02/10 23:56:02 INFO Utils: Successfully started service 'sparkDriver' on port 38874.
> 16/02/10 23:56:02 INFO SparkEnv: Registering MapOutputTracker
> 16/02/10 23:56:02 INFO SparkEnv: Registering BlockManagerMaster
> 16/02/10 23:56:02 INFO DiskBlockManager: Created local directory at /tmp/spark-ad4ad5d7-f7a7-4077-b28f-9b7640df6be7/blockmgr-602b044d-1230-4292-ac04-521e49451f8a
> 16/02/10 23:56:02 INFO MemoryStore: MemoryStore started with capacity 265.4 MB
> 16/02/10 23:56:02 INFO HttpFileServer: HTTP File server directory is /tmp/spark-ad4ad5d7-f7a7-4077-b28f-9b7640df6be7/httpd-7fc446a4-2228-4833-8b20-160419a20be1
> 16/02/10 23:56:02 INFO HttpServer: Starting HTTP Server
> 16/02/10 23:56:02 INFO Utils: Successfully started service 'HTTP file server' on port 57591.
> 16/02/10 23:56:02 INFO SparkEnv: Registering OutputCommitCoordinator
> 16/02/10 23:56:02 INFO Utils: Successfully started service 'SparkUI' on port 4040.
> 16/02/10 23:56:02 INFO SparkUI: Started SparkUI at http://10.0.0.1:4040
> 16/02/10 23:56:02 INFO SparkContext: Added JAR file:/usr/local/adam/adam-cli/target/adam-cli_2.10-0.18.0.jar at http://10.0.0.1:57591/jars/adam-cli_2.10-0.18.0.jar with timestamp 1455148562803
> 16/02/10 23:56:02 INFO Executor: Starting executor ID driver on host localhost
> 16/02/10 23:56:02 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 54978.
> 16/02/10 23:56:02 INFO NettyBlockTransferService: Server created on 54978
> 16/02/10 23:56:02 INFO BlockManagerMaster: Trying to register BlockManager
> 16/02/10 23:56:02 INFO BlockManagerMasterEndpoint: Registering block manager localhost:54978 with 265.4 MB RAM, BlockManagerId(driver, localhost, 54978)
> 16/02/10 23:56:03 INFO BlockManagerMaster: Registered BlockManager
> 16/02/10 23:56:03 INFO MemoryStore: ensureFreeSpace(166040) called with curMem=0, maxMem=278302556
> 16/02/10 23:56:03 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 162.1 KB, free 265.3 MB)
> 16/02/10 23:56:04 INFO MemoryStore: ensureFreeSpace(15651) called with curMem=166040, maxMem=278302556
> 16/02/10 23:56:04 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 15.3 KB, free 265.2 MB)
> 16/02/10 23:56:04 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:54978 (size: 15.3 KB, free: 265.4 MB)
> 16/02/10 23:56:04 INFO SparkContext: Created broadcast 0 from newAPIHadoopFile at ADAMContext.scala:441
> 16/02/10 23:56:04 INFO ADAMRDDFunctions: Saving data in ADAM format
> 16/02/10 23:56:04 INFO deprecation: mapred.output.dir is deprecated. Instead, use mapreduce.output.fileoutputformat.outputdir
> 16/02/10 23:56:04 INFO FileInputFormat: Total input paths to process : 1
> Command body threw exception:
> htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: unexpected tag count 3 in line <ID=PASS,Description="All filters passed",IDX=0>
> 16/02/10 23:56:04 INFO Vcf2ADAM: Overall Duration: 2.99 secs
> Exception in thread "main" htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: unexpected tag count 3 in line <ID=PASS,Description="All filters passed",IDX=0>
>     at htsjdk.variant.vcf.VCF4Parser.parseLine(VCFHeaderLineTranslator.java:109)
>     at htsjdk.variant.vcf.VCFHeaderLineTranslator.parseLine(VCFHeaderLineTranslator.java:51)
>     at htsjdk.variant.vcf.VCFSimpleHeaderLine.<init>(VCFSimpleHeaderLine.java:66)
>     at htsjdk.variant.vcf.VCFFilterHeaderLine.<init>(VCFFilterHeaderLine.java:62)
>     at htsjdk.variant.vcf.AbstractVCFCodec.parseHeaderFromLines(AbstractVCFCodec.java:202)
>     at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:111)
>     at htsjdk.variant.bcf2.BCF2Codec.readHeader(BCF2Codec.java:176)
>     at org.seqdoop.hadoop_bam.BCFSplitGuesser.<init>(BCFSplitGuesser.java:107)
>     at org.seqdoop.hadoop_bam.BCFSplitGuesser.<init>(BCFSplitGuesser.java:88)
>     at org.seqdoop.hadoop_bam.VCFInputFormat.addGuessedSplits(VCFInputFormat.java:254)
>     at org.seqdoop.hadoop_bam.VCFInputFormat.fixBCFSplits(VCFInputFormat.java:242)
>     at org.seqdoop.hadoop_bam.VCFInputFormat.getSplits(VCFInputFormat.java:221)
>     at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:95)
>     at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
>     at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
>     at scala.Option.getOrElse(Option.scala:120)
>     at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
>     at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:32)
>     at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
>     at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
>     at scala.Option.getOrElse(Option.scala:120)
>     at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
>     at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:32)
>     at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
>     at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
>     at scala.Option.getOrElse(Option.scala:120)
>     at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
>     at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:32)
>     at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
>     at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
>     at scala.Option.getOrElse(Option.scala:120)
>     at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
>     at org.apache.spark.SparkContext.runJob(SparkContext.scala:1774)
>     at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1055)
>     at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:998)
>     at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:998)
>     at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
>     at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
>     at org.apache.spark.rdd.RDD.withScope(RDD.scala:286)
>     at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:998)
>     at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply$mcV$sp(PairRDDFunctions.scala:938)
>     at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:930)
>     at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:930)
>     at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
>     at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
>     at org.apache.spark.rdd.RDD.withScope(RDD.scala:286)
>     at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:930)
>     at org.apache.spark.rdd.InstrumentedPairRDDFunctions.saveAsNewAPIHadoopFile(InstrumentedPairRDDFunctions.scala:487)
>     at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply$mcV$sp(ADAMRDDFunctions.scala:75)
>     at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply(ADAMRDDFunctions.scala:60)
>     at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply(ADAMRDDFunctions.scala:60)
>     at org.apache.spark.rdd.Timer.time(Timer.scala:57)
>     at org.bdgenomics.adam.rdd.ADAMRDDFunctions.adamParquetSave(ADAMRDDFunctions.scala:60)
>     at org.bdgenomics.adam.rdd.ADAMRDDFunctions.adamParquetSave(ADAMRDDFunctions.scala:46)
>     at org.bdgenomics.adam.cli.Vcf2ADAM.run(Vcf2ADAM.scala:76)
>     at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:54)
>     at org.bdgenomics.adam.cli.Vcf2ADAM.run(Vcf2ADAM.scala:55)
>     at org.bdgenomics.adam.cli.ADAMMain.apply(ADAMMain.scala:121)
>     at org.bdgenomics.adam.cli.ADAMMain$.main(ADAMMain.scala:77)
>     at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:606)
>     at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:665)
>     at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:170)
>     at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:193)
>     at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:112)
>     at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> 16/02/10 23:56:04 INFO SparkContext: Invoking stop() from shutdown hook
> 16/02/10 23:56:04 INFO SparkUI: Stopped Spark web UI at http://10.0.0.1:4040
> 16/02/10 23:56:04 INFO DAGScheduler: Stopping DAGScheduler
> 16/02/10 23:56:04 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
> 16/02/10 23:56:04 INFO Utils: path = /tmp/spark-ad4ad5d7-f7a7-4077-b28f-9b7640df6be7/blockmgr-602b044d-1230-4292-ac04-521e49451f8a, already present as root for deletion.
> 16/02/10 23:56:04 INFO MemoryStore: MemoryStore cleared
> 16/02/10 23:56:04 INFO BlockManager: BlockManager stopped
> 16/02/10 23:56:04 INFO BlockManagerMaster: BlockManagerMaster stopped
> 16/02/10 23:56:04 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
> 16/02/10 23:56:04 INFO SparkContext: Successfully stopped SparkContext
> 16/02/10 23:56:04 INFO Utils: Shutdown hook called
> 16/02/10 23:56:04 INFO Utils: Deleting directory /tmp/spark-ad4ad5d7-f7a7-4077-b28f-9b7640df6be7``

**Comment by davidonlaptop** [comment]
Hi zhanx,

Thanks for your feedback. It looks like an error with your VCF file

*Exception in thread "main" htsjdk.tribble.TribbleException$InvalidHeader:
Your input file has a malformed header: unexpected tag count 3 in line *

Have you tried with a different VCF file to see if you have the same error ?

-David

**Comment by zhanxw** [comment]
The plain VCF files (without compression) worked. 

I tried to remove the line beginning with "##FILTER.." and stored the file in BCF format, then vcf2adam also worked. 

Can you replicate this problem on your side?

Thanks. 
Xiaowei

**Comment by davidonlaptop** [comment]
Hi Zhanx,

This appears to be a bug in ADAM itself. You should report it on their
GitHub https://github.com/bigdatagenomics/adam or mailing list
http://bdgenomics.org/mail/.

I should probably update the docker image to the latest ADAM version.
Perhaps the bug is fixed there. If that is the case, let me know and I'll
try to release a new image quickly.

Best regards,

-David

**Comment by zhanxw** [comment]
Hi David,

I will check the github repo of ADAM. 

The docker image is easier for me to get start learning ADAM. Hope the image gets updated soon.

Thanks.

**Comment by davidonlaptop** [comment]
Hi Zhanx,

Yes, the goal of this repo is to make it easier to learn ADAM. Ideally I
should make a pull request to the ADAM guys so they can keep the docker
image in sync with ADAM releases. I'll try to look into that shortly.

In the meantime, I've updated the Dockerfile to the latest version of ADAM.
Here's how you can build it:

git pull

cd adam-0.18/
docker build -t adam:0.18.2 .

This will create a local image "adam:0.18.2" in your computer.

Hope this helps,

Best regards,
David
